name: Docker Build Trigger

on:
  push:
    # Build on all branch pushes, not PRs for security
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  trigger-docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Docker build workflow in builder repository
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.BUILDER_REPO_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository_owner }}/ai-dev-workflow-builder/dispatches \
          -d '{
            "event_type": "docker-build-event",
            "client_payload": {
              "repository": "${{ github.repository }}",
              "repository_owner": "${{ github.repository_owner }}",
              "ref_name": "${{ github.ref_name }}",
              "sha": "${{ github.sha }}"
            }
          }'