name: Build and Deploy Docker Images

on:
  push:
    # Build on all branch pushes, not PRs for security
    branches: [ '**' ]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: org-runners-couleetechlinkinc

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Extract metadata
      id: meta
      run: |
        # Set image names and tags
        ORG_NAME="$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')"
        REPO_NAME="claude-workflow-docker"
        BRANCH_NAME="${{ github.ref_name }}"
        
        # Strip timestamp from claude/ branches (claude/issue-1-20250708_210355 -> claude/issue-1)
        CLEAN_BRANCH_NAME="$BRANCH_NAME"
        if [[ "$BRANCH_NAME" == claude/* ]]; then
          CLEAN_BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's/-[0-9]\{8\}_[0-9]\{6\}$//')
        fi
        
        SHORT_SHA="${{ github.sha }}"
        SHORT_SHA_TAG="${SHORT_SHA:0:8}"
        
        # GitHub Container Registry (3-level namespace)
        GHCR_IMAGE="ghcr.io/${ORG_NAME}/${REPO_NAME}/${CLEAN_BRANCH_NAME}"
        
        # Docker Hub (2-level namespace)
        DOCKERHUB_IMAGE="couleetech/ai-developer"
        
        echo "=== Image Build Information ==="
        echo "Repository: ${{ github.repository }}"
        echo "Branch: $BRANCH_NAME"
        echo "Clean Branch: $CLEAN_BRANCH_NAME"
        echo "Commit SHA: ${SHORT_SHA_TAG}"
        echo "GHCR Image: $GHCR_IMAGE"
        echo "Docker Hub Image: $DOCKERHUB_IMAGE"
        echo "=============================="
        
        # Set outputs for use in build step
        echo "ghcr-image=$GHCR_IMAGE" >> $GITHUB_OUTPUT
        echo "dockerhub-image=$DOCKERHUB_IMAGE" >> $GITHUB_OUTPUT
        echo "branch-tag=$CLEAN_BRANCH_NAME" >> $GITHUB_OUTPUT
        echo "sha-tag=$SHORT_SHA_TAG" >> $GITHUB_OUTPUT

    - name: Build and push Docker images
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ steps.meta.outputs.ghcr-image }}:latest
          ${{ steps.meta.outputs.ghcr-image }}:${{ steps.meta.outputs.sha-tag }}
          ${{ steps.meta.outputs.dockerhub-image }}:${{ steps.meta.outputs.branch-tag }}
          ${{ steps.meta.outputs.dockerhub-image }}:${{ steps.meta.outputs.sha-tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max