name: Claude Code Docker Trigger

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  trigger-claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Trigger Claude workflow in builder repository
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.BUILDER_REPO_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository_owner }}/ai-dev-workflow-builder/dispatches \
            -d '{
              "event_type": "claude-event",
              "client_payload": {
                "repository": "${{ github.repository }}",
                "event": ${{ toJSON(github.event) }}
              }
            }'